#!/bin/bash

echo "VERCEL_ENV: $VERCEL_ENV"
echo "NEXT_PUBLIC_VERCEL_ENV: $NEXT_PUBLIC_VERCEL_ENV"
echo "gitBranch: $(git branch)"
echo "gitBranchMain: $(git branch | grep main)"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF: $NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF"

echo "VERCEL:->  $VERCEL <<--END-->>"
echo "CI:->  $CI <<--END-->>"
echo "VERCEL_ENV:->  $VERCEL_ENV <<--END-->>"
echo "VERCEL_URL:->  $VERCEL_URL <<--END-->>"
echo "VERCEL_REGION:->  $VERCEL_REGION <<--END-->>"
echo "VERCEL_GIT_PROVIDER:->  $VERCEL_GIT_PROVIDER <<--END-->>"
echo "VERCEL_GIT_REPO_SLUG:->  $VERCEL_GIT_REPO_SLUG <<--END-->>"
echo "VERCEL_GIT_REPO_OWNER:->  $VERCEL_GIT_REPO_OWNER <<--END-->>"
echo "VERCEL_GIT_REPO_ID:->  $VERCEL_GIT_REPO_ID <<--END-->>"
echo "VERCEL_GIT_COMMIT_REF:->  $VERCEL_GIT_COMMIT_REF <<--END-->>"
echo "VERCEL_GIT_COMMIT_SHA:->  $VERCEL_GIT_COMMIT_SHA <<--END-->>"
echo "VERCEL_GIT_COMMIT_MESSAGE:->  $VERCEL_GIT_COMMIT_MESSAGE <<--END-->>"
echo "VERCEL_GIT_COMMIT_AUTHOR_LOGIN:->  $VERCEL_GIT_COMMIT_AUTHOR_LOGIN <<--END-->>"
echo "VERCEL_GIT_COMMIT_AUTHOR_NAME:->  $VERCEL_GIT_COMMIT_AUTHOR_NAME <<--END-->>"
echo "NEXT_PUBLIC_VERCEL:->  $NEXT_PUBLIC_VERCEL <<--END-->>"
echo "NEXT_PUBLIC_CI:->  $NEXT_PUBLIC_CI <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_ENV:->  $NEXT_PUBLIC_VERCEL_ENV <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_URL:->  $NEXT_PUBLIC_VERCEL_URL <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_REGION:->  $NEXT_PUBLIC_VERCEL_REGION <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_PROVIDER:->  $NEXT_PUBLIC_VERCEL_GIT_PROVIDER <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG:->  $NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_REPO_OWNER:->  $NEXT_PUBLIC_VERCEL_GIT_REPO_OWNER <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_REPO_ID:->  $NEXT_PUBLIC_VERCEL_GIT_REPO_ID <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF:->  $NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA:->  $NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_MESSAGE:->  $NEXT_PUBLIC_VERCEL_GIT_COMMIT_MESSAGE <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_LOGIN:->  $NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_LOGIN <<--END-->>"
echo "NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_NAME:->  $NEXT_PUBLIC_VERCEL_GIT_COMMIT_AUTHOR_NAME <<--END-->>"

if [[ "$VERCEL_ENV" == "production" ]] ; then
  # Proceed with the build
  echo "✅ - Build can proceed"
  exit 1;

else
  # Don't build
  echo "🛑 - Build cancelled"
  exit 0;
fi